max-power-per-faction: 20
min-power-per-faction: -10
max-power-increase-per-player: 5
max-land-per-player: 5
max-faction-size: 5
power-regen-time: 5
power-regen-amount: 0.5
power-lose-per-death: 0.5
frozen-duration: 5
claim-cost: 5000
claim-cost-increase-per-chunk: 1000
home-cooldown: 5
denied-commands-in-factions:
  - "/sethome"
  - "/tpahere"


messages:
  enter-title: "&4&l%faction%"
  max-members: "&C&l(!)&C You cannot invite more players into your faction!"
  max-members-join: "&C&l(!)&c This faction is full!"
  teleport-into-faction: "&C&l(!)&C You cannot teleport into a faction!"
  max-land-reached: "&c&l(!)&c You cannot claim more land than this!"
  enter-subtitle: "&c%description%"
  claim-message: "&4&l(!)&c You have successfully claimed this chunk."
  denied-message: "&4&l(!)&c You cannot execute that command here."
  balance-message: "&4&l(!)&c Your faction currently has $%amount% in it's balance."
  sethome: "&a&l(!)&a Your faction home has been set."
  home: "&a&l(!)&a Teleporting you to your faction home in 5 seconds..."
  delhome: "&c&l(!)&c Your faction home has been deleted."
  create-broadcast: "&4[Factions]&c the faction &l%faction%&c has just been created!"
  create-message: "&a&l(!)&a You have successfully created your faction."
  disband-broadcast: "&4[Factions]&c the faction &l%faction%&c has been disbanded!"
  disband-message: "&4&l(!)&c Your faction has been disbanded."
  invite-message-player: "&a&l(!)&a Successfully invited %player% to your faction"
  invite-message-target: "&a&l(!)&a You have been invited to %faction%. Do /faction join to join!"
  invite-message-faction: "&a&l(!)&a %player% has been invited to your faction!"
  revoke-message-player: "&a&l(!)&a Successfully revoked %player%'s invite."
  revoke-message-target: "&c&l(!)&c Your invite to %faction% has been revoked."
  join-message: "&a&l(!)&a %player% has joined your faction!"
  leave-message-player: "&a&l(!)&a You have successfully left %faction%."
  leave-message-faction: "&C&l(!)&c %player% has left your faction!"
  chat-enter: "&a&l(!)&a You have successfully entered the faction chat."
  chat-leave: "&a&l(!)&a You have successfully left the faction chat."
  transfer: "&a&l(!)&a The factions leadership has been transferred to %player%."
  open: "&a&l(!)&a The faction %faction% has been opened for anyone to join!"
  close: "&C&l(!)&c The faction %faction% has been closed from the public."
  deposit: "&a&l(!)&a %player% has deposited &a$%amount%&a to your factions balance."
  withdraw: "&c&l(!)&c %player% has withdrawn &a$%amount%&a from your factions balance."
  kick: "&C&l(!)&c You have been kicked from your faction."
  kick-faction: "&c&l(!)&c %player% has been kicked from your faction!"
  description: "&a&l(!)&a Your factions description has been updated to %description%"
  top-header: "&4Factions Top &7(Kills)"
  top-template: "&c#%rank%   &7⛨%name%   &c❤ %kills%"
  list-header: "&4Factions List &7(Players Online)"
  list-template: "&4&l»&r &f%name%&r &7(&a● &7 %online%/%size%)"
  info:
    - "&4%faction% Info"
    - ""
    - "&7⛨ &6%faction%"
    - "&c❖ &fTeam Ranking: &6%rank%"
    - ""
    - "&fLeader: &7%leader%"
    - "&fCo-Leader: &7%coleader%"
    - "&fOfficers: &7%officers%"
    - "&fMembers: &7%members%"
    - ""
    - "&fDescription: %description%"
    - ""
  info-frozen:
    - "&4%faction% Info"
    - ""
    - "&7⛨ &6%faction%"
    - "&c❖ &fTeam Ranking: &6%rank%"
    - ""
    - "&fLeader: &7%leader%"
    - "&fCo-Leader: &7%coleader%"
    - "&fOfficers: &7%officers%"
    - "&fMembers: &7%members%"
    - ""
    - "&fDescription: %description%"
    - ""