name: LuckyblockFactions
version: '${project.version}'
main: me.nootnoot.luckyblockfactions.LuckyblockFactions
api-version: 1.18
authors: [ nootnoot ]
description: Factions core for Luckyblock
website: https://avalondev.net
depend: [dynmap]
commands:
  faction:
    aliases: [f, factions]
    description: Command for factions.
