name: JackpotMCCrashGambling
version: '${project.version}'
main: me.nootnoot.jackpotmccrashgambling.JackpotMCCrashGambling
api-version: 1.18
authors: [nootnoot]
description: Crash gambling plugin for JackpotMC
website: https://avalondev.net
commands:
  crashgamble:
    description: Command for the plugin
