name: LuckyblockBackpacks
version: '${project.version}'
main: me.nootnoot.luckyblockbackpacks.LuckyblockBackpacks
api-version: 1.18
authors: [nootnoot]
description: Custom backpack plugin for Luckyblock
website: https://avalondev.net
commands:
  backpack:
    description: Main command
    aliases: [bp]
