name: JackpotMCTeams
version: '${project.version}'
main: me.nootnoot.jackpotmcteams.JackpotMCTeams
api-version: 1.18
authors: [ nootnoot ]
description: Teams plugin for JackpotMC
website: https://avalondev.net
commands:
  team:
    description: "Main command for teams."
    aliases: [teams]
  teamadmin:
    description: "Main command for teams (admin commands)."
    aliases: [teamsadmin]
    permission: "JackpotMCTeams.admin"
