#how often one should spawn. (in minutes)
spawn-time: 30
#When the airdrop should be removed, if it's not looted. (In minutes)
remove-time: 5
#How many should spawn at once?
amount: 5
broadcast-message: "&eAn &6&lAIRDROP &ehas just spawned at: &lx:%x%, y:%y%, z:%z%"
airdrops:
  spawn-radius:
    world: "world"
    #x and z values have 50% chance to be negative.
    x: 100
    z: 100
  COMMON:
    name: "&bCommon"
    #chance of this rarity spawning
    #MAKE SURE THIS DOES NOT GO OVER 100.
    spawn-chance: 50
  UNCOMMON:
    name: "&eUncommon"
    spawn-chance: 35
  RARE:
    name: "&6Rare"
    spawn-chance: 15