global-cooldown: 30
use-recipes: true
glow: false
items:
  zap_stick:
    hit_count: 3
    cooldown: 60
    item:
      name: "&bZap Stick"
      material: STICK
      lore:
        - "&7Zap your enemies"
    #1st parameter = effect, 2nd parameter = level, 3rd parameter is duration in seconds.
    effects:
      source: []
      target:
        - "blindness;1;8"
        - "weakness;1;8"
    #1st parameter = particle, 2nd parameter = amount;
    particles:
      - "cloud;5"
    sounds:
      source:
        1:
          name: "ENTITY_EXPERIENCE_ORB_PICKUP"
          volume: 1.0
          pitch: 0.7
        2:
          name: "ENTITY_LIGHTNING_BOLT_IMPACT"
          volume: 1.0
          pitch: 2.0
      target:
        1:
  blacksmith:
    hit_count: 0
    cooldown: 60
    item:
      name: "&bBlacksmith"
      material: FIREWORK_STAR
      lore:
        - "&7Right click to repair your armor"
    #1st parameter = effect, 2nd parameter = level, 3rd parameter is duration in seconds.
    effects:
      source: []
      target: []
    particles:
      - "cloud;5"
    sounds:
      source:
        1:
          name: "BLOCK_ANVIL_USE"
          volume: 1.0
          pitch: 0.7
      target:
        1:
  strength_rod:
    hit_count: 0
    cooldown: 60
    item:
      name: "&bStrength rod"
      material: BLAZE_ROD
      lore:
        - "&7Right click to give yourself strength"
    #1st parameter = effect, 2nd parameter = level, 3rd parameter is duration in seconds.
    effects:
      source:
        - "increase_damage;3;8"
      target: []
    particles:
      - "cloud;5"
    sounds:
      source:
        1:
          name: "BLOCK_ANVIL_USE"
          volume: 1.0
          pitch: 0.7
      target:
        1:
  crits_multiplier:
    hit_count: 0
    cooldown: 60
    multiplier: 1.25
    duration: 30
    item:
      name: "&bCrits Multiplier"
      material: BLAZE_POWDER
      lore:
        - "&7Right click to give yourself &e1.5x &7damage multiplier"
    #1st parameter = effect, 2nd parameter = level, 3rd parameter is duration in seconds.
    effects:
      source: []
      target: []
    particles:
      - "cloud;5"
    sounds:
      source:
        1:
          name: "AMBIENT_CAVE"
          volume: 0.8
          pitch: 2.0
      target:
        1:
  elytra_disabler:
    hit_count: 3
    cooldown: 60
    duration: 60
    item:
      name: "&bElytra Disabler"
      material: QUARTZ
      lore:
        - "&7Hit your enemy 3 times to disable their elytra for 60 seconds!"
    #1st parameter = effect, 2nd parameter = level, 3rd parameter is duration in seconds.
    effects:
      source: []
      target: []
    particles:
      - "cloud;5"
    sounds:
      source:
        1:
          name: "ENTITY_ENDER_DRAGON_FLAP"
          volume: 0.8
          pitch: 1.4
      target:
        1:
          name: "ENTITY_ENDER_DRAGON_FLAP"
          volume: 0.8
          pitch: 1.4
  levitator:
    hit_count: 3
    cooldown: 60
    item:
      name: "&bLevitator"
      material: FEATHER
      lore:
        - "&7Hit your enemy 3 times to send them flying!"
    #1st parameter = effect, 2nd parameter = level, 3rd parameter is duration in seconds.
    effects:
      source: []
      target:
        - "levitation;2;60"
    particles:
      - "cloud;5"
    sounds:
      source:
        1:
          name: "BLOCK_BREWING_STAND_BREW"
          volume: 1.0
          pitch: 0.7
      target:
        1:
          name: "BLOCK_BREWING_STAND_BREW"
          volume: 1.0
          pitch: 0.7
  deflector:
    hit_count: 0
    duration: 30
    cooldown: 60
    item:
      name: "&bDeflector"
      material: SHIELD
      lore:
        - "&7Activate this to block all negative potion effects from arrows"
    #1st parameter = effect, 2nd parameter = level, 3rd parameter is duration in seconds.
    effects:
      source: []
      target: []
    particles:
      - "cloud;5"
    sounds:
      source:
        1:
          name: "BLOCK_BREWING_STAND_BREW"
          volume: 1.0
          pitch: 0.7
      target:
        1:
          name: "BLOCK_BREWING_STAND_BREW"
          volume: 1.0
          pitch: 0.7
  cloud:
    hit_count: 0
    duration: 0
    amountToFlyUp: 30
    cooldown: 60
    item:
      name: "&bCloud"
      material: FEATHER
      lore:
        - "&7Make yourself fly up and glide away!"
    #1st parameter = effect, 2nd parameter = level, 3rd parameter is duration in seconds.
    effects:
      source: []
      target: []
    particles:
      - "cloud;5"
    sounds:
      source:
        1:
          name: "BLOCK_BREWING_STAND_BREW"
          volume: 1.0
          pitch: 0.7
      target:
        1:
          name: "BLOCK_BREWING_STAND_BREW"
          volume: 1.0
          pitch: 0.7