luckyblock-material: SPONGE
y-level: 0

tiers:
  common:
    name: "&eCommon Luckyblock"
    spawn-chance: 10
  uncommon:
    name: "&eUncommon Luckyblock"
    spawn-chance: 5
  rare:
    name: "&eRare Luckyblock"
    spawn-chance: 2