name: JackpotMCCombat
version: '${project.version}'
main: me.nootnoot.jackpotmccombat.JackpotMCCombat
api-version: 1.18
authors: [ nootnoot ]
description: Combat plugin for JackpotMC
website: https://avalondev.net
depend: [WorldGuard]
softdepend: [KoTH]
commands:
  pvp:
    description: Command for grace
