name: JackpotMCDailyRewards
version: '${project.version}'
main: me.nootnoot.jackpotmcdailyrewards.JackpotMCDailyRewards
api-version: 1.18
authors: [ nootnoot ]
description: Daily spin rewards plugin for JackpotMC
website: https://avalondev.net
commands:
  dailyrewards:
    description: Command for daily rewards.
    aliases: [dailyreward]
