name: LuckyBlockOreRegen
version: '${project.version}'
main: me.nootnoot.luckyblockoreregen.LuckyBlockOreRegen
api-version: 1.18
authors: [ nootnoot ]
description: Ore regeneration plugin for Lucky Block
website: https://avalondev.net
commands:
  customblock:
    description: Main command.
